version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: addissoftwar
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/girma/AddisSoftwar/songs-backend/addissoftwar/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped